# Generated by Django 5.1 on 2025-12-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('club', 'Club'), ('activity', 'Activity')], help_text='Unique slug: club or activity', max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='promo_cards/')),
                ('link', models.URLField(blank=True, help_text='Full URL or relative path to page')),
            ],
            options={
                'verbose_name': 'Promo Card',
                'verbose_name_plural': 'Promo Cards',
            },
        ),
    ]
