# Generated by Django 5.1 on 2025-12-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_options_remove_activity_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date']},
        ),
    ]
